### ISSUE TITLE
Get-InstallCommand - spaces in filename

### ISSUE THREAD

**Issue by Boss-man** [byteben/Win32App-Migration-Tool#11]
I have a $SetupFile variable as this: msiexec /i "Print Settings 1.0.1.msi" /q
The resulting $command is "1.0.1.msi", which is not right.

Don't know if spaces in the filename can be handled somehow.

**Comment by Boss-man** [comment]
> It depends on how you defined the variable, did you surround it with single quotes? e.g. $SetupFile = 'msiexec /i "Print Settings 1.0.1.msi" /q'

I don't define it, it's in the source code in the Get-InstallCommand function. And it takes the value from the SCCM application install command.

**Comment by byteben** [comment]
Interesting :)
Maybe I’m not handling escapes chars very well. I’ll take a look, thank you

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Boss-man ***@***.***>
Sent: Monday, November 13, 2023 11:46:57 AM
To: byteben/Win32App-Migration-Tool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [byteben/Win32App-Migration-Tool] Get-InstallCommand - spaces in filename (Issue #11)


I have a $SetupFile variable as this: msiexec /i "Print Settings 1.0.1.msi" /q
The resulting $command is "1.0.1.msi", which is not right.

Don't know if spaces in the filename can be handled somehow.

**Comment by obuolinis** [comment]
Ben, you're splitting the $SetupFile line first by $InstallTech (.msi in this case) and then by a " " (space), that's why you end up with just "1.0.1.msi".
To be able to handle filenames with spaces your Get-InstallCommand function would require a different splitting logic. And I'm afraid it could not be very straightforward to come up with a one-fits-all version - I mean how do you tell whether a space is part of a filename or not?

**Comment by cclifton7** [comment]
In New-IntuneWin.ps1 I changed `$fileToCheck = $commandToUse -replace '\..*', '.intunewin'` to  `$fileToCheck = $commandToUse -replace ".{4}$", '.intunewin'` so the extension is dropped off the install command.

**Comment by byteben** [comment]
Semi-confident this is now fixed in 2.0.19 branch @Boss-man 
Replace Get-InstallCommand.ps1 in your module directory with the one from branch https://github.com/byteben/Win32App-Migration-Tool/tree/version-2.0.19 and let me know. Thank you.
