### ISSUE TITLE
Why not use Get-CMApplication -Name for Get-AppList.ps1?

### ISSUE THREAD

**Issue by obuolinis** [byteben/Win32App-Migration-Tool#13]
Ben, why are you retrieving the whole list of CM apps and then do filtering by name on the client side when you can make use of the "Name" parameter of Get-CMApplication supporting wildcards and let the server do the filtering?

My environment (300+ apps):
- 3-4s for `$apps = Get-CMApplication -Fast | Where-Object { $_.LocalizedDisplayName -like "*java*" }`
- <1s for `$apps = Get-CMApplication -Name "*java*" -Fast`

**Comment by byteben** [comment]
What is the speed difference when using the -fast switch in your environment between the 2 commands?

**Comment by obuolinis** [comment]
But I already used -Fast above... Or you mean with and without -Fast?

- `$apps = Get-CMApplication | Where-Object { $_.LocalizedDisplayName -like "*java*" }`
this takes insanely long
- `$apps = Get-CMApplication -Name "*java*"`
this completes in 1-1.5s

**Comment by byteben** [comment]
When you say insanely long, what do you mean? In your first comment you indicated it took 3-4 seconds?

**Comment by obuolinis** [comment]
Ben, my first measurement/comment included -Fast parameter, my second one didn't :)

**Comment by byteben** [comment]
Which function/line are you referring to please?

**Comment by obuolinis** [comment]
https://github.com/byteben/Win32App-Migration-Tool/blob/bb7955920c2ff3386fa8b446f3b203e2dda298ea/Private/Get-AppList.ps1#L55
This and all the other "Get-CMApplication -Fast" references in the same file.

**Comment by byteben** [comment]
https://github.com/byteben/Win32App-Migration-Tool/pull/14
