### ISSUE TITLE
New feature in development: Get-DetectionMethods

### ISSUE THREAD

**Issue by obuolinis** [byteben/Win32App-Migration-Tool#16]
We're in early stages of migrating all our packaged apps from SCCM to Intune and I came up with an idea that we could make use of Win32App-Migration-Tool combined with IntuneWin32App - the former doing the job of exporting the app and the latter of importing.
Unfortunately, your project has been stuck for quite a while in the beta stage and doesn't even handle a full export of a SCCM app... :( Do you still intend to develop this further Ben?

Even if you don't perhaps you could help me out with the Get-DetectionMethods feature? I have a raw (half-working) version in my fork:
https://github.com/obuolinis/Win32App-Migration-Tool/blob/d3e54598c254b1b7624b311a50b1bee8f882a92d/Private/Get-DetectionMethods.ps1 (updated a broken link)
Also, some necessary changes in New-Win32App to support it:
https://github.com/obuolinis/Win32App-Migration-Tool/commit/d3e54598c254b1b7624b311a50b1bee8f882a92d#diff-4fc9ecf4be5f2c45f36d33af4e80484f5426c55a5066b925713fe9ca0a8eb357

However, I'm facing certain challenges with the function itself and its integration into the whole flow, specifically:

1. I can't decide which function to call Get-DetectionMethods from. Since detection is part of a deployment type it makes most sense to call it from Get-DeploymentTypeInfo and add detection methods as part of its output. However, in that case one property of the Get-DeploymentTypeInfo output would have a value of an array of detection methods, which would be impossible for Export-CsvDetails to handle.
2. Another option is calling Get-DetectionMethods from the main function New-Win32App, which is what I have implemented. The downside is that this means additional calls to SCCM from Get-DetectionMethods and consequently longer processing time.
3. A second issue is that a built-in SCCM cmdlet Get-CMDeploymentTypeDetectionClause isn't able to handle script detection methods, at least it didn't work for me. So I had to use another way for those - the app SDMPackageXML property.
4. The next issue stems from a previous one - how to handle different output formats of the two types of detection methods within Get-DetectionMethods? I'm yet to decide on what to do with the script type. There are only two things of interest - a script body and RunAs32Bit property. The former could go to a file, the latter could be part of a file name. But then what to return to the calling function when there's nothing left to return? Of course we need to pass that file name so perhaps a deployment type id, a detection method type (script), a file name and RunAs32Bit? Hm that could work.

So there you go, ideas are welcome.

**Comment by byteben** [comment]
Yes I intend to develop it further. The beta code base just went through a refactor to v2 - that was long overdue. I have more code to get the rest of the dt info in a private repo almost ready to merge

**Comment by cclifton7** [comment]
@obuolinis and @byteben , take a look at my fork when you get a chance. I managed to combined Win32App-Migration-Tool with IntuneWin32App (https://github.com/MSEndpointMgr/IntuneWin32App) and created detection method functions to allow a fully automated method to upload ConfigMgr apps to Intune.  I have been working on this for longer than I care to admit. I've successfully uploaded almost all of our apps into Intune with it.

https://github.com/cclifton7/Win32App-Migration-Tool

**Comment by byteben** [comment]
Thanks Casey, I’ll take a look. You did what I have in my private repo so I’m curious on your approach.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by byteben** [comment]
Will be cool to see. I'll be exporting detection methods to a JSON file on disk so I can port it directly to my Graph Request - still in a private repo just now

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by byteben** [comment]
> We're in early stages of migrating all our packaged apps from SCCM to Intune and I came up with an idea that we could make use of Win32App-Migration-Tool combined with IntuneWin32App - the former doing the job of exporting the app and the latter of importing. Unfortunately, your project has been stuck for quite a while in the beta stage and doesn't even handle a full export of a SCCM app... :( Do you still intend to develop this further Ben?
> 
> Even if you don't perhaps you could help me out with the Get-DetectionMethods feature? I have a raw (half-working) version in my fork: https://github.com/obuolinis/Win32App-Migration-Tool/blob/main/Private/Get-DetectionMethods.ps1 Also, some necessary changes in New-Win32App to support it: [obuolinis@d3e5459#diff-4fc9ecf4be5f2c45f36d33af4e80484f5426c55a5066b925713fe9ca0a8eb357](https://github.com/obuolinis/Win32App-Migration-Tool/commit/d3e54598c254b1b7624b311a50b1bee8f882a92d#diff-4fc9ecf4be5f2c45f36d33af4e80484f5426c55a5066b925713fe9ca0a8eb357)
> 
> However, I'm facing certain challenges with the function itself and its integration into the whole flow, specifically:
> 
> 1. I can't decide which function to call Get-DetectionMethods from. Since detection is part of a deployment type it makes most sense to call it from Get-DeploymentTypeInfo and add detection methods as part of its output. However, in that case one property of the Get-DeploymentTypeInfo output would have a value of an array of detection methods, which would be impossible for Export-CsvDetails to handle.
> 2. Another option is calling Get-DetectionMethods from the main function New-Win32App, which is what I have implemented. The downside is that this means additional calls to SCCM from Get-DetectionMethods and consequently longer processing time.
> 3. A second issue is that a built-in SCCM cmdlet Get-CMDeploymentTypeDetectionClause isn't able to handle script detection methods, at least it didn't work for me. So I had to use another way for those - the app SDMPackageXML property.
> 4. The next issue stems from a previous one - how to handle different output formats of the two types of detection methods within Get-DetectionMethods? I'm yet to decide on what to do with the script type. There are only two things of interest - a script body and RunAs32Bit property. The former could go to a file, the latter could be part of a file name. But then what to return to the calling function when there's nothing left to return? Of course we need to pass that file name so perhaps a deployment type id, a detection method type (script), a file name and RunAs32Bit? Hm that could work.
> 
> So there you go, ideas are welcome.

I really like the work and thought here. Looking at the Get-DetectionMethods.ps1 script, it looks like you are only returning an object if the detection provider is a script. I cannot see the script get added to a $detectionMethods object...
You are on the same track as me to be honest. At the moment, I am still debating whether to call the DT from the public script or the Get-DeploymentTypeInfo function - If I do the later, ill output 2 objects and use the first one to build CSV details and the second to create an XML on disk for detection methods

**Comment by obuolinis** [comment]
I was undecided at the time which path to go, the version of Get-DetectionMethods.ps1 that I shared here was just a draft.
I've now uploaded my final working version which I renamed to Get-DetectionMethodInfo to follow your naming pattern. I'm calling it from the public function New-Win32App, lines 272-278:
https://github.com/obuolinis/Win32App-Migration-Tool/blob/fc11fea27d1242e15c14fd80d8dca837fcf4322f/Public/New-Win32App.ps1#L272
Lines 315-322 take care of exporting detection methods to csv (+ps1 if it's a script):
https://github.com/obuolinis/Win32App-Migration-Tool/blob/fc11fea27d1242e15c14fd80d8dca837fcf4322f/Public/New-Win32App.ps1#L315
And I've just noticed I messed up the regions within New-Win32App, oh well... :)

**Comment by obuolinis** [comment]
And here's my app migration script that combines Win32App-Migration-Tool with IntuneWin32App:
https://github.com/obuolinis/Win32App-Migration-Tool/blob/main/migrate-sccm-app-to-intune-public.ps1

It's a standalone script, not integrated with the module (I'm using the private Write-Log function from it though). It's quite straightforward, apart from the detection method conversion for which I wrote 2 helper functions. The script has certain limitations:

- only 1 app and 1 deployment type per csv file is supported;
- app requirements' migration is not implemented;
- doesn't make sure no empty params are passed to Add-IntuneWin32App (which it doesn't like, for example Description),

There's also one thing to be aware of with regards to detection method migration - in some cases like for like migration isn't possible due to Intune limitations:

- any file size-based detection rules (bytes in SCCM, MB in Intune);
- some detection operators aren't supported;
- detection rule connector "OR" isn't supported (haven't implemented this check in my script).

**Comment by byteben** [comment]
I created a new branch, 2.0.20 and this has an updated Get-DeploymentTypeInfo.ps1 which now pulls detection method information from the deployment type and saves the script or MethodBody to disk as an XML. Im working on saving the script with the correct encoding and filetype in another PR this weekend for 2.0.20

**Comment by byteben** [comment]
Update in branch 2.0.20: We now parse all local detection methods from the XML and create a JSON ready to pass to the Win32app.
