### ISSUE TITLE
Only 1 Application built

### ISSUE THREAD

**Issue by JonseyFTW** [byteben/Win32App-Migration-Tool#17]
First, love the tool. I'm having to convert about 120 applications from SCCM into Intune with the slow migration of getting more workloads into Intune in our hybrid environment. Here is the line I am running

`New-Win32App -SiteCode "CCC" -ProviderMachineName "CCC.contoso.local" -AppName "*Seven*" -WorkingFolder "I:\IntuneApps" -ExportIcon -DownloadContent -PackageApps -CreateApps -ResetLog`

I noticed whenever I will select multiple applications is only builds 1 of the applications.

![image](https://github.com/byteben/Win32App-Migration-Tool/assets/34360611/83d130ec-7c55-4cd5-8b6c-febfd59d9422)

![image](https://github.com/byteben/Win32App-Migration-Tool/assets/34360611/19ac0f87-25d1-4051-a2e6-190a03cc360e)

You can see it does notice there are 2 applications that were selected but then it only actually creates the contents, .intunewin, and detail CSVs file for just 1
![image](https://github.com/byteben/Win32App-Migration-Tool/assets/34360611/af446591-33e6-45af-b5f1-2d329cb2c31f)
![image](https://github.com/byteben/Win32App-Migration-Tool/assets/34360611/1e040684-c991-4fd8-a8e2-b875dd426e17)
![image](https://github.com/byteben/Win32App-Migration-Tool/assets/34360611/b9706413-ddd3-40c9-9940-ab235e248ce0)

**Comment by byteben** [comment]
Thanks for raising this. I found a bug in Get-AppInfo.ps1 where I was returning objects inside of the foreach loop. This is fixed in Branch Version-2.0.20 [https://github.com/byteben/Win32App-Migration-Tool/tree/version-2.0.20](https://github.com/byteben/Win32App-Migration-Tool/tree/version-2.0.20)
