### ISSUE TITLE
Fails to detect setup file

### ISSUE THREAD

**Issue by SimonRingrow** [byteben/Win32App-Migration-Tool#18]
New-Win32App ... -PackageApps fails to build the .intunewin file if it doesn't find find a setup file with an extension it recognises.

With vb-script being deprecated I have recently started converting my vb-script files to j-script.

The setup wrapper I used was for my installation was a j-script .js file.

To resolve the issue I added the following if statement into my local copy of New-Intunewin.ps1

elseif ($SetupFile -match "\.js") {
$commandToUse = Get-InstallCommand -InstallTech '.js' -SetupFile $SetupFile
}

**Comment by byteben** [comment]
Thanks Simon. I added support for .js files in [branch version-2.0.20](https://github.com/byteben/Win32App-Migration-Tool/tree/version-2.0.20)
