### ISSUE TITLE
-Wait on IntuneWinAppUtil command

### ISSUE THREAD

**Issue by philschwan** [byteben/Win32App-Migration-Tool#2]
Running with the -PackageApps and -CreateApps command arguments, it attempts to create the .intunewin file with IntuneWinAppUtil.exe but fails to do so.  Looking at the log, it's passing -Wait as though it's a command line argument for IntuneWinAppUtil instead of Start-Process
![image](https://user-images.githubusercontent.com/27557859/112379709-df1fa500-8cbe-11eb-8035-a9ff2655ddbc.png)

**Comment by byteben** [comment]
Thanks for the feedback. The "CreateApps" switch doesn't work in BETA so it wont perform any function - yet.
The -Wait argument is not passed to IntuneWinAppUtil.exe, it is part of the Start-Process cmdlet and is an accepted command.

![image](https://user-images.githubusercontent.com/44303264/112381446-7d713200-8ce2-11eb-872d-56c1403b5f5e.png)

Are you able to run the IntuneWinAppUtil.exe manually for that Deployment Type out of interest from the same content folder? Are we picking up the correct executable name?

**Comment by philschwan** [comment]
Yeah, realized right after that I should have tried it manually. Getting an
odd error:
[image: image.png]

**Comment by byteben** [comment]
Hey, I cant see the image you posted. If you are getting an error when building the .intunewin manually double check the content folder is as you would expect in **%SystemDrive%\Win32AppMigrationTool\Content\<Deployment Type GUID>**

**Comment by philschwan** [comment]
Adding image again. It's a dependency issue with IntuneWinAppUtil.  I rebuilt the command line manually and still get the same. I did verify the content is in the source folder, so it's definitely something IntuneWinAppUtil is missing.
![image](https://user-images.githubusercontent.com/27557859/112464539-ffd91080-8d39-11eb-9c9a-35866dafdeb2.png)

**Comment by philschwan** [comment]
Updated the .NET version on this system (Server 2016, CM primary) and after reboot appears to have resolved the issue. Log led me down the wrong path where manual testing revealed the real issue. Thanks for the quick responses.

**Comment by byteben** [comment]
Well found! Ill take a look at the docs and see if it mentions a specific .Net Framework version requirement for the Content Prep Tool. Thanks for the feedback!
