### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by kapilkathuria** [byteben/Win32App-Migration-Tool#21]
Hello,

Not really an issue to raise. I just wanted to check if this project is being actively developed? 

Blog post of 2021 shows that project was in Beta in 2021. Currently Github seems to show that Project is Beta. I assume functionality available is as per attached image shown under column Beta, and anything mentioned under Release & GA are not available.
![image](https://github.com/user-attachments/assets/bfc93858-0efb-4d50-abcd-f09e65e076d3)

If project is still Beta and is being actively developed, is any tentative timeline to reach GA?

PS: pls advise if you are looking for contribution to project.

**Comment by byteben** [comment]
Hey. There is an updated branch that isn’t main that has further improvements. I’m hoping for end to end migration around Jan/Feb 2025

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: kapilkathuria ***@***.***>
Sent: Tuesday, December 24, 2024 1:18:15 PM
To: byteben/Win32App-Migration-Tool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [byteben/Win32App-Migration-Tool] Quick question (Issue #21)


Hello,

Not really an issue to raise. I just wanted to check if this project is being actively developed?

Blog post of 2021 shows that project was in Beta in 2021. Currently Github seems to show that Project is Beta. I assume functionality available is as per attached image shown under column Beta, and anything mentioned under Release & GA are not available.
image.png (view on web)<https://github.com/user-attachments/assets/bfc93858-0efb-4d50-abcd-f09e65e076d3>

If project is still Beta and is being actively developed, is any tentative timeline to reach GA?

PS: pls advise if you are looking for contribution to project.

**Comment by kapilkathuria** [comment]
Thanks for your quick revert, much appreciated

**Comment by byteben** [comment]
The latest version 3.0.3 in Preview supports end to end now @kapilkathuria
