### ISSUE TITLE
IntuneWinApputil.exe could not load file or assembly. Win32App creation fails

### ISSUE THREAD

**Issue by hotzenwalder** [byteben/Win32App-Migration-Tool#3]
Generating the Win32App fails and the content folder is empty after running the command.
When I run the generated IntuneWinAppUtil.exe.exe command manually it throws an error

`ERROR  File 'C:\Win32AppMigrationTool\Win32Apps\Application_4cb79509-5ae7-47d2-80a9-13461f3baea1\DeploymentType_bd6026d1
-9306-408f-aba6-70a48d48358d\setup.intunewin' has failed to be generated

[===========                                      ]   22%
INFO   Done!!!

ERROR  System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Compression, Version=4.2.0.0, Culture
=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
File name: 'System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.CreateFromDirectory(String sourceDirectoryName, String desti
nationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, ReportProgress reportProgress)
   at Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.ZipFolder(String folder, String zipFile, AppContext context,
 Boolean noCompression, Boolean includeBaseDirectory, Boolean appendFile)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String ou
tputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
`
The system is running Windows Server 2012 R2 almost the latest build, but not the latest. .Net Framework. I think it might have something to do with that. Can you confirm it needs a minimum version of .Net framework installed on the server?

Installed .Net Framework versions

![image](https://user-images.githubusercontent.com/78266646/112723912-18e7ea00-8f11-11eb-94da-d35fdb0bc34e.png)

Error in Powershell

![image](https://user-images.githubusercontent.com/78266646/112723937-361cb880-8f11-11eb-8917-524f188bb529.png)

Application I am testing with is Microsoft Apps for 365. All other applications I try fail with the same error.

**Comment by byteben** [comment]
Hey, I believe there is a .NET Framework requirement for the Win32 Content Prep Tool but I couldn’t see anything in the MS docs. Let me confirm..

Kind Regards
Ben

Sent from my iPhone

On 27 Mar 2021, at 14:31, hotzenwalder ***@***.***> wrote:

﻿

Generating the Win32App fails and the content folder is empty after running the command.
When I run the generated IntuneWinAppUtil.exe.exe command manually it throws an error

`ERROR File 'C:\Win32AppMigrationTool\Win32Apps\Application_4cb79509-5ae7-47d2-80a9-13461f3baea1\DeploymentType_bd6026d1
-9306-408f-aba6-70a48d48358d\setup.intunewin' has failed to be generated

[=========== ] 22%
INFO Done!!!

ERROR System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Compression, Version=4.2.0.0, Culture
=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
File name: 'System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
at Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.CreateFromDirectory(String sourceDirectoryName, String desti
nationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, ReportProgress reportProgress)
at Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.ZipFolder(String folder, String zipFile, AppContext context,
Boolean noCompression, Boolean includeBaseDirectory, Boolean appendFile)
at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String ou
tputFolder, String catalogFolder)
at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
`
The system is running Windows Server 2012 R2 almost the latest build, but not the latest. .Net Framework. I think it might have something to do with that. Can you confirm it needs a minimum version of .Net framework installed on the server?

Installed .Net Framework versions

[image]<https://user-images.githubusercontent.com/78266646/112723912-18e7ea00-8f11-11eb-94da-d35fdb0bc34e.png>

Error in Powershell

[image]<https://user-images.githubusercontent.com/78266646/112723937-361cb880-8f11-11eb-8917-524f188bb529.png>

Application I am testing with is Microsoft Apps for 365. All other applications I try fail with the same error.

**Comment by hotzenwalder** [comment]
IntuneWinApputil.exe runs from the command line on the server. I think the process where the content should be compressed is missing a component or dependency. Thanks for taking the time to look into this issue.

Kind regards,

Marcel Moerings

**Comment by byteben** [comment]
Hi, .NET Framework 4.7.2 is required to run the Win32 Content Prep Tool - I have added this to the pre-requisite list. Thank you.
