### ISSUE TITLE
Package Multiple sources

### ISSUE THREAD

**Issue by Floribloo** [byteben/Win32App-Migration-Tool#4]
I tried to convert an application where the sources of install and uninstall are not the same. But both have a setup.exe file. 

The first problem I have is that the way the robot copy command is done it adds the two paths in one and gives an error "path not found".

Example: 
**source install:** 
\server\pkg\Src\Microsoft\Office 365\EN\

**source uninstall:** 
\server\pkg\Src\Microsoft\Office 365\Uninstaller\ 

When it tries to copy the path that it uses is a path formed by the two destinations separated by a space. 

**In the log we can read:** 
Downloading Content for Deployment Type DeploymentType_6793e21e-b717-44db-8328-61b202c1898a from Content Source \\server\pkg\Src\Microsoft\Office 365\EN\ \\server\pkg\Src\Microsoft\Office 365\Uninstaller\...

 ERROR 3 (0x00000003) Accessing Source Directory \\server\pkg\Src\Microsoft\Office 365\EN \server\pkg\Src\Microsoft\Office 365\Uninstaller\

then I can't run a test like I want to validate if two sources with the same name file will work. 

Yves

**Comment by byteben** [comment]
Thanks for the feedback @Floribloo . I've added this into the "Bugs" section as I believe there is mishandling of syntax when the uninstall content path differs from the install content path. Thanks for flagging it.

**Comment by byteben** [comment]
This is being fixed in the refactor for version 2

**Comment by byteben** [comment]
This has now been addressed in V2.x, thank you for the feedback. If the Application has different uninstall content, we create an "Uninstall" folder in the content folder.
