### ISSUE TITLE
Garbled characters in Japanese environment

### ISSUE THREAD

**Issue by hidemaruki** [byteben/Win32App-Migration-Tool#6]
Thank you for developing amazing tool!

If [Application_Name] [Application_Description] contains 2 bytes, it will be output and [Applications.csv] will be output as garbled characters in Japanese environment.

If possible, I'm glad that you make this code support for double-byte character languages.

My project has 2,000 app migrations from MECM to Intune, so I'm looking forward to GA development as well

![MECM_app1](https://user-images.githubusercontent.com/77660914/155487300-54296442-ac56-453f-a918-97092af32715.jpg)
![MECM_app2](https://user-images.githubusercontent.com/77660914/155487870-3ec30ef1-4fcb-45ac-812f-0c117811a326.png)

**Comment by hidemaruki** [comment]
The problem was resolved after adding "Encoding UTF8" to New-Win32App.ps1 where it outputs DeploymentTypes.csv, Applications.csv and Content.csv.

Could you fix the source code with reference below?

[Before modification]$DeploymentTypes_Array | Export-Csv (Join-Path -Path $WorkingFolder_Detail -ChildPath "DeploymentTypes.csv") -NoTypeInformation -Force

[After modification]$DeploymentTypes_Array | Export-Csv (Join-Path -Path $WorkingFolder_Detail -ChildPath "DeploymentTypes.csv") -NoTypeInformation -Force -Encoding UTF8

**Comment by byteben** [comment]
Thanks for your input, I have modified the code and added UTF8 encoding for all instances where the CSV is exported
