### ISSUE TITLE
Name files/folders after app name?

### ISSUE THREAD

**Issue by Boss-man** [byteben/Win32App-Migration-Tool#7]
Hi

When using the tool the resulting *.intunewin file is named after the install command.
In my case we use PSADT so the install command is "Deploy-Application.exe", resulting in "Deploy-Application.intunewin"

Would it be possible to name the files/folders after the app name like "7-Zip", "Adobe Reader" and so on ?
Maybe a folder structure like: App-name --> App-version --> App-name.intunewin

**Comment by byteben** [comment]
Looking to improve on this for the refactor in version 2

**Comment by Boss-man** [comment]
Just tried the new version. Works much better now. 
Maybe put the logo in the top folder of the program folder ? Or give the logo name like app-name.jpg|png ?

**Comment by byteben** [comment]
Added an optional parameter in V2.x $OverrideIntuneWin32FileName that allows you to specify a custom .intunewin name. Please log a new PR for other considerations like changing the logo name, thanks
